# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mcagr/lab_1.1/lab_1.1.cache/wt [current_project]
set_property parent.project_path C:/Users/mcagr/lab_1.1/lab_1.1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/mcagr/lab_1.1/lab_1.1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/mcagr/lab_1.1/lab1_template/lab_1.1.srcs/sources_1/new/MonPro.vhd
  C:/Users/mcagr/lab_1.1/lab1_template/ascii_rom.vhd
  C:/Users/mcagr/lab_1.1/lab1_template/bcd_ascii.vhd
  C:/Users/mcagr/lab_1.1/lab1_template/debounce.vhd
  C:/Users/mcagr/lab_1.1/lab1_template/delay.vhd
  C:/Users/mcagr/lab_1.1/lab_1.1.srcs/sources_1/new/mont_mult.vhd
  C:/Users/mcagr/lab_1.1/lab1_template/oled_drive.vhd
  C:/Users/mcagr/lab_1.1/lab1_template/oled_init.vhd
  C:/Users/mcagr/lab_1.1/lab1_template/spi_ctrl.vhd
  C:/Users/mcagr/lab_1.1/lab1_template/mod_mul_with_oled.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/mcagr/Desktop/lab1_template/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/mcagr/Desktop/lab1_template/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mod_mul_with_oled -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mod_mul_with_oled.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mod_mul_with_oled_utilization_synth.rpt -pb mod_mul_with_oled_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
