set_property PACKAGE_PIN Y9 [get_ports clk]
create_clock -period 100.000 -name CLK -waveform {0.000 50.000} [get_ports clk]

set_property PACKAGE_PIN Y11 [get_ports sonar_echo]
set_property IOSTANDARD LVCMOS33 [get_ports sonar_echo]
set_property PACKAGE_PIN AA11 [get_ports sonar_trig]
set_property IOSTANDARD LVCMOS33 [get_ports sonar_trig]

set_property PACKAGE_PIN T22 [get_ports {output_ones[0]}]
set_property PACKAGE_PIN T21 [get_ports {output_ones[1]}]
set_property PACKAGE_PIN U22 [get_ports {output_ones[2]}]
set_property PACKAGE_PIN U21 [get_ports {output_ones[3]}]
set_property PACKAGE_PIN V22 [get_ports {output_tens[0]}]
set_property PACKAGE_PIN W22 [get_ports {output_tens[1]}]
set_property PACKAGE_PIN U19 [get_ports {output_tens[2]}]
set_property PACKAGE_PIN U14 [get_ports {output_tens[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {output_ones[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_ones[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_ones[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_ones[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_tens[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_tens[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_tens[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_tens[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
