# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mcagr/lab4_2014/lab4_2014.cache/wt [current_project]
set_property parent.project_path C:/Users/mcagr/lab4_2014/lab4_2014.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
set_property ip_repo_paths {
  c:/Users/mcagr/lab4_2014/multiplier_ip_0/multiplier_ip_2014
  c:/Users/mcagr/lab4_2014/multiplier_ip_1
  c:/Users/mcagr/lab4_2014/multiplier_ip_0
  c:/Users/mcagr/lab4_2014
  c:/Users/mcagr/lab4_2014/ip
  C:/Users/mcagr/ip_repo
} [current_project]
add_files -quiet C:/Users/mcagr/lab4_2014/lab4_2014.runs/system_synth_1/system.dcp
set_property used_in_implementation false [get_files C:/Users/mcagr/lab4_2014/lab4_2014.runs/system_synth_1/system.dcp]
read_vhdl -library xil_defaultlib C:/Users/mcagr/lab4_2014/lab4_2014.srcs/sources_1/bd/system/hdl/system_wrapper.vhd
read_xdc C:/Users/mcagr/lab_4/lab4_zedboard.xdc
set_property used_in_implementation false [get_files C:/Users/mcagr/lab_4/lab4_zedboard.xdc]

catch { write_hwdef -file system_wrapper.hwdef }
synth_design -top system_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef system_wrapper.dcp
catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
